### ISSUE TITLE
Users with an Author Profile are unable to click into the All Posts Dashboard page

### ISSUE THREAD

**Issue by BigActual** [realbig/RBM-Projects-Theme#11]
When they click on Posts or All Posts in the left nav on the dashboard, the system boots them out to the homepage instead of showing the posts dashboard. This is a critical issue because I have training for the atuhors at 10am today. 

I used the user switching plugin to review their ability to get into the posts dashboard. I tried Ann Zalek and Molly Delucia. both had the same problem.

I tried my pc and my mac. Same result on both machines.

There is an editing workflow plugin installed. I am wholly planning on using this software. It's part of my 10am curriculum.

Thanks,
Steve

**Comment by d4mation** [comment]
Meant to be opened here: https://github.com/VLSLgithub/VL-theme-V1/issues/68
