### ISSUE TITLE
Can't load project dashboard

### ISSUE THREAD

**Issue by BigActual** [realbig/RBM-Projects-Theme#2]
requires login, but login is a circular loop.

**Comment by joelworsham** [comment]
ugh

**Comment by joelworsham** [comment]
Seems to be a corrupt login cookie issue. Go to the network dashboard for the whole multisite, https://realbigmarketing.com/wp-admin/network/, and then log out from there. Then go back to the projects page and log in again. If it gives you a cookie error, try again.

**Comment by d4mation** [comment]
Interesting. This would be a Project Panorama bug then, wouldn't it?

**Comment by joelworsham** [comment]
Possibly.  I talked to Ross and he wasn't sure.

**Comment by BigActual** [comment]
Maybe this has been fixed with the upgrade to SSL?

**Comment by d4mation** [comment]
I noticed it didn't give me any trouble, but wasn't sure if it was a fluke. It never gave me too many problems to begin with. Just required logging in when going between SSL and non-SSL sites on the Multi-site.
