### ISSUE TITLE
Please change the downloads slug to plans

### ISSUE THREAD

**Issue by BigActual** [realbig/RBM-Projects-Theme#5]
https://docs.easydigitaldownloads.com/article/594-edd-slug

**Comment by d4mation** [comment]
We have this set up on RBM.com. Are you wanting it on Projects instead? It is already that Slug over there.

**Comment by BigActual** [comment]
yes, on projects.realbigmarketing.com. I'll be taking it off of the root domain.

**Comment by d4mation** [comment]
All set. I had made this into a plugin, so I just had to activate it on projects.realbigmarketing.com.

You'll want to deactivate the plugin off the root domain when you're set.

https://github.com/realbig/rbm-support-tiers
